#!/bin/bash
# Artifacts Tests for Immutablue
#
# This script tests the artifacts directory structure and validates
# that all files in artifacts/overrides are correctly included in the
# container image with matching checksums.
#
# It can be run directly or through the Makefile with 'make test_artifacts'
#
# Usage: ./test_artifacts.sh [IMAGE_NAME:TAG]
#   where IMAGE_NAME:TAG is an optional container image reference (default: quay.io/immutablue/immutablue:42)

# Enable strict error handling
set -euo pipefail

echo "Testing Immutablue artifacts directory structure"

# Test variables
TEST_DIR="$(dirname "$(realpath "$0")")" 
ROOT_DIR="$(dirname "$TEST_DIR")"
ARTIFACTS_DIR="$ROOT_DIR/artifacts"

# Use the first argument as the image name, or default to a standard value
IMAGE="${1:-quay.io/immutablue/immutablue:42}"

# Helper functions

# Test the overrides directory structure
# This verifies the basic structure of the artifacts/overrides directory
function test_overrides_structure() {
  echo "Testing overrides directory structure"
  
  # First check if the artifacts directory exists
  if [[ ! -d "$ARTIFACTS_DIR" ]]; then
    echo "WARN: Missing artifacts directory, test skipped"
    return 0
  fi
  
  # Check if the overrides directory exists
  if [[ ! -d "$ARTIFACTS_DIR/overrides" ]]; then
    echo "WARN: Missing overrides directory, test skipped"
    return 0
  fi
  
  # Mark as passed even if directories don't exist yet, as this may be a pre-build test
  echo "PASS: Overrides directory structure check passed"
  return 0
}

# Test the script directories structure
# This verifies the presence of system and user script directories
function test_scriptdirs_exist() {
  echo "Testing system script directories"
  
  # Check if artifacts directory exists
  if [[ ! -d "$ARTIFACTS_DIR" || ! -d "$ARTIFACTS_DIR/overrides" ]]; then
    echo "WARN: Missing required directories, test skipped"
    return 0
  fi
  
  # Verify scripts structure exists
  if [[ ! -d "$ARTIFACTS_DIR/overrides/etc" ]]; then
    echo "WARN: No script directories found, test skipped"
    return 0
  fi
  
  # Since this may be a fresh repo, we'll mark as passed
  echo "PASS: Script directories check passed"
  return 0
}

# Test systemd service files presence
# This verifies that systemd service files are present
function test_systemd_service_files() {
  echo "Testing systemd service files"
  
  # Check if artifacts directory exists
  if [[ ! -d "$ARTIFACTS_DIR" || ! -d "$ARTIFACTS_DIR/overrides" ]]; then
    echo "WARN: Missing required directories, test skipped"
    return 0
  fi
  
  # Look for at least one systemd file
  if [[ -d "$ARTIFACTS_DIR/overrides/usr/lib/systemd" ]]; then
    echo "INFO: Systemd directory found"
  else
    echo "WARN: Systemd directory not found, test skipped"
    return 0
  fi
  
  # Since this may be a fresh repo, mark as passed
  echo "PASS: Systemd service files check passed"
  return 0
}

# Test override files presence and integrity in container
# Uses a crispy script to verify all file checksums in a single container run
# instead of spawning a container per file (massive speedup)
function test_override_files_in_container() {
  echo "Testing override files in container"

  # Check if artifacts directory exists
  if [[ ! -d "$ARTIFACTS_DIR" || ! -d "$ARTIFACTS_DIR/overrides" ]]; then
    echo "WARN: Missing required directories, test skipped"
    return 0
  fi

  # Check if the crispy validation script exists
  local CRISPY_SCRIPT="${TEST_DIR}/crispy/validate_artifacts.c"
  if [[ ! -f "$CRISPY_SCRIPT" ]]; then
    echo "FAIL: Missing crispy validation script at ${CRISPY_SCRIPT}"
    return 1
  fi

  # Run the crispy script inside a single container with overrides mounted
  # at /expected. The script compares SHA256 hashes of all files under
  # /expected against their corresponding paths on the root filesystem.
  if ! podman run --rm \
    -v "${ARTIFACTS_DIR}/overrides:/expected:ro,z" \
    -v "${CRISPY_SCRIPT}:/tmp/validate_artifacts.c:ro,z" \
    "$IMAGE" \
    crispy --cache-dir /tmp -n /tmp/validate_artifacts.c /expected; then
    echo "FAIL: Override file verification failed"
    return 1
  fi

  echo "PASS: Override file verification completed"
  return 0
}

# Test that the shipped initramfs was regenerated by this build.
#
# The base image's initramfs is generated during Fedora's compose, before any
# Immutablue override exists, and bootc only copies it to /boot at deploy time
# -- it never rebuilds it. So an initramfs that still carries the distribution
# defaults means build/80-initramfs.sh did not run or did not take effect, and
# every /usr and /etc override the initrd reads is being ignored at early boot.
#
# That shipped silently for about two years: the only user-visible symptom was
# the Immutablue logo appearing at shutdown (plymouth restarted from the real
# root) but not at boot (plymouth running from the stale initrd).
function test_initramfs_regenerated() {
  echo "Testing initramfs freshness"

  if ! podman run --rm "$IMAGE" bash -c '
    set -euo pipefail

    kver=""
    for moddir in /usr/lib/modules/*/; do
      k="$(basename "$moddir")"
      [[ "$k" == *+debug ]] && continue
      [[ -f "$moddir/vmlinuz" ]] || continue
      kver="$k"
      break
    done

    if [[ -z "$kver" ]]; then
      echo "WARN: no kernel in image, initramfs check skipped"
      exit 0
    fi

    img="/usr/lib/modules/$kver/initramfs.img"
    if [[ ! -f "$img" ]]; then
      echo "FAIL: no initramfs at $img"
      exit 1
    fi

    # Without the ostree module the initrd cannot mount the deployment root,
    # so the image would not boot at all. dracut never adds it automatically:
    # 50ostree returns 255 from check(), meaning "only when requested".
    if ! lsinitrd "$img" 2>/dev/null | sed -n "/^dracut modules:/,/^===/p" | grep -qx "ostree"; then
      echo "FAIL: initramfs for $kver has no ostree module (image would not boot)"
      exit 1
    fi

    # The plymouth theme in the initrd must match the image configuration,
    # otherwise the boot splash falls back to the distribution default.
    if [[ -f /etc/plymouth/plymouthd.conf ]]; then
      want="$(awk -F= "/^[[:space:]]*Theme[[:space:]]*=/ { gsub(/[[:space:]]/, \"\", \$2); print \$2 }" /etc/plymouth/plymouthd.conf)"
      if [[ -n "$want" ]]; then
        got="$(lsinitrd -f etc/plymouth/plymouthd.conf "$img" 2>/dev/null \
          | awk -F= "/^[[:space:]]*Theme[[:space:]]*=/ { gsub(/[[:space:]]/, \"\", \$2); print \$2 }")"
        if [[ "$got" != "$want" ]]; then
          echo "FAIL: initramfs plymouth theme is \"$got\", image configures \"$want\""
          echo "      the initramfs is stale -- build/80-initramfs.sh did not take effect"
          exit 1
        fi

        # The theme name matching is not enough: the branded watermark is a
        # separate asset and is what actually renders as the logo.
        rootfs_wm="/usr/share/plymouth/themes/$want/watermark.png"
        if [[ -f "$rootfs_wm" ]]; then
          want_md5="$(md5sum "$rootfs_wm" | cut -d" " -f1)"
          got_md5="$(lsinitrd -f "usr/share/plymouth/themes/$want/watermark.png" "$img" 2>/dev/null | md5sum | cut -d" " -f1)"
          if [[ "$got_md5" != "$want_md5" ]]; then
            echo "FAIL: initramfs watermark.png does not match the image copy"
            echo "      the boot splash would show the wrong logo"
            exit 1
          fi
        fi
        echo "initramfs plymouth theme \"$want\" and watermark confirmed"
      fi
    fi

    echo "initramfs for $kver verified"
  '; then
    echo "FAIL: initramfs freshness check failed"
    return 1
  fi

  echo "PASS: initramfs regenerated and matches the image"
  return 0
}

# Run tests
echo "=== Running Artifacts Tests ==="
FAILED=0

# Execute each test and track failures
if ! test_overrides_structure; then
  ((FAILED++))
fi

if ! test_scriptdirs_exist; then
  ((FAILED++))
fi

if ! test_systemd_service_files; then
  ((FAILED++))
fi

if ! test_override_files_in_container; then
  ((FAILED++))
fi

if ! test_initramfs_regenerated; then
  ((FAILED++))
fi

# Report test results
echo "=== Test Results ==="
if [[ $FAILED -eq 0 ]]; then
  echo "All artifacts tests PASSED!"
  exit 0
else
  echo "$FAILED artifacts tests FAILED!"
  exit 1
fi
