#!/bin/bash
# ==============================================================================
# Immutablue Image Configuration Generator
# ==============================================================================
# Generates bootc-image-builder config.toml files for various image types.
# Supports interactive user configuration or auto-generation modes.
#
# Usage: generate-image-config.sh <type> <output_path> [options]
#
# Types: iso, raw, ami, gce, vhd, vmdk, qcow2, anaconda-iso
#
# Options:
#   --lima          Auto-add Lima SSH keys (for qcow2)
#   --classic       Use classic ISO mode (for iso)
#   --non-interactive  Generate minimal config without prompts
#   --no-user       Generate config without user (firstboot enabled for iso)
# ==============================================================================

set -euo pipefail

TYPE="${1:-}"
OUTPUT="${2:-}"
shift 2 2>/dev/null || true

LIMA=0
CLASSIC=0
NON_INTERACTIVE=0
NO_USER=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --lima)
            LIMA=1
            shift
            ;;
        --classic)
            CLASSIC=1
            shift
            ;;
        --non-interactive)
            NON_INTERACTIVE=1
            shift
            ;;
        --no-user)
            NO_USER=1
            shift
            ;;
        *)
            shift
            ;;
    esac
done

if [[ -z "$TYPE" ]] || [[ -z "$OUTPUT" ]]; then
    echo "Usage: $0 <type> <output_path> [options]"
    echo "Types: iso, raw, ami, gce, vhd, vmdk, qcow2, anaconda-iso"
    echo "Options: --lima, --classic, --non-interactive, --no-user"
    exit 1
fi

TYPE_UPPER=$(echo "$TYPE" | tr '[:lower:]' '[:upper:]' | tr '-' '_')

write_config_header() {
    local output="$1"
    cat > "$output" <<EOF
# Immutablue ${TYPE} configuration
# Generated by: make ${TYPE}-config
# Auto-generated file - do not edit manually

EOF
}

write_user_config() {
    local output="$1"
    local username="$2"
    local password="$3"
    local wheel="$4"
    local ssh_key="$5"

    cat >> "$output" <<EOF

[[customizations.user]]
name = "${username}"
password = "${password}"
EOF

    if [[ "$wheel" != "n" ]] && [[ "$wheel" != "N" ]]; then
        echo 'groups = ["wheel"]' >> "$output"
    fi

    if [[ -n "$ssh_key" ]]; then
        echo "key = \"${ssh_key}\"" >> "$output"
    fi
}

prompt_for_user() {
    local add_user
    read -p "Add a user account? [y/N]: " add_user

    if [[ "$add_user" != "y" ]] && [[ "$add_user" != "Y" ]]; then
        return 1
    fi

    local username
    read -p "Username [immutablue]: " username
    username="${username:-immutablue}"

    local password
    read -s -p "Password: " password
    echo

    if [[ -z "$password" ]]; then
        echo "Error: Password cannot be empty."
        return 1
    fi

    local add_wheel
    read -p "Add to wheel group (sudo access)? [Y/n]: " add_wheel

    local ssh_key=""
    local add_ssh

    if [[ "$LIMA" -eq 1 ]]; then
        echo ""
        echo "LIMA=1 detected - auto-adding SSH key..."
        if [[ -f "$HOME/.lima/_config/user.pub" ]]; then
            ssh_key=$(cat "$HOME/.lima/_config/user.pub")
            echo "Added Lima SSH key from ~/.lima/_config/user.pub"
        elif [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
            ssh_key=$(cat "$HOME/.ssh/id_ed25519.pub")
            echo "Added SSH key from ~/.ssh/id_ed25519.pub"
        elif [[ -f "$HOME/.ssh/id_rsa.pub" ]]; then
            ssh_key=$(cat "$HOME/.ssh/id_rsa.pub")
            echo "Added SSH key from ~/.ssh/id_rsa.pub"
        else
            echo "Warning: LIMA=1 but no SSH key found."
        fi
    fi

    if [[ -z "$ssh_key" ]]; then
        read -p "Add SSH public key? [y/N]: " add_ssh
        if [[ "$add_ssh" == "y" ]] || [[ "$add_ssh" == "Y" ]]; then
            echo ""
            echo "Available SSH keys:"
            ls -1 ~/.ssh/*.pub 2>/dev/null || echo "  (none found in ~/.ssh/)"
            if [[ -f "$HOME/.lima/_config/user.pub" ]]; then
                echo "  $HOME/.lima/_config/user.pub (Lima)"
            fi
            echo ""

            local ssh_key_path
            read -p "Path to SSH public key [~/.ssh/id_ed25519.pub]: " ssh_key_path
            ssh_key_path="${ssh_key_path:-~/.ssh/id_ed25519.pub}"
            ssh_key_path=$(eval echo "$ssh_key_path")

            if [[ -f "$ssh_key_path" ]]; then
                ssh_key=$(cat "$ssh_key_path")
                echo "Added SSH key from $ssh_key_path"
            else
                echo "Warning: SSH key not found at $ssh_key_path, skipping."
            fi
        fi
    fi

    echo ""
    echo "User '$username' configured."

    write_user_config "$OUTPUT" "$username" "$password" "$add_wheel" "$ssh_key"
    return 0
}

generate_minimal_config() {
    local output="$1"

    if [[ "$TYPE" == "iso" ]] && [[ "$CLASSIC" -ne 1 ]]; then
        cat > "$output" <<EOF
# Immutablue ISO config - interactive first-boot setup
# Enable GNOME Initial Setup on first boot for:
# - User account creation
# - Timezone selection
# - Language/keyboard settings

[customizations.installer.kickstart]
contents = """
firstboot --enable
"""
EOF
    else
        cat > "$output" <<EOF
# Immutablue ${TYPE} config - no users configured
# Run 'make ${TYPE}-config' to add user accounts
EOF
    fi
}

generate_lima_config() {
    local output="$1"

    mkdir -p "$(dirname "$output")"

    cat > "$output" <<EOF
# Auto-generated bootc-image-builder config (LIMA=1)

[[customizations.user]]
name = "immutablue"
password = "immutablue"
groups = ["wheel"]
EOF

    if [[ -f "$HOME/.lima/_config/user.pub" ]]; then
        echo "key = \"$(cat "$HOME/.lima/_config/user.pub")\"" >> "$output"
        echo "Added Lima SSH key to config"
    elif [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
        echo "key = \"$(cat "$HOME/.ssh/id_ed25519.pub")\"" >> "$output"
        echo "Added SSH key (id_ed25519) to config"
    elif [[ -f "$HOME/.ssh/id_rsa.pub" ]]; then
        echo "key = \"$(cat "$HOME/.ssh/id_rsa.pub")\"" >> "$output"
        echo "Added SSH key (id_rsa) to config"
    else
        echo "Warning: LIMA=1 but no SSH key found. Lima SSH access may not work."
    fi
}

generate_default_config() {
    local output="$1"

    mkdir -p "$(dirname "$output")"

    cat > "$output" <<EOF
# Auto-generated bootc-image-builder config

[[customizations.user]]
name = "immutablue"
password = "immutablue"
groups = ["wheel"]
EOF
}

mkdir -p "$(dirname "$OUTPUT")"

if [[ "$NO_USER" -eq 1 ]] || [[ "$NON_INTERACTIVE" -eq 1 ]]; then
    generate_minimal_config "$OUTPUT"
elif [[ "$LIMA" -eq 1 ]] && [[ ! -t 0 ]]; then
    generate_lima_config "$OUTPUT"
elif [[ ! -t 0 ]]; then
    generate_default_config "$OUTPUT"
else
    echo "=== Immutablue ${TYPE_UPPER:-$TYPE} Configuration ==="
    echo "Config file: $OUTPUT"
    echo ""

    write_config_header "$OUTPUT"

    if ! prompt_for_user "$OUTPUT"; then
        generate_minimal_config "$OUTPUT"
    fi

    echo ""
    echo "Configuration saved to: $OUTPUT"
    echo "Run 'make ${TYPE}' to build the ${TYPE} image."
fi
