# ==============================================================================
# Immutablue Build System - Build Targets
# ==============================================================================
# This file contains all container build and push targets.
# ==============================================================================

# ------------------------------------------------------------------------------
# Container ignore files
# ------------------------------------------------------------------------------
# Two builds share one context (the repo root) but want different exclusions:
# the deps container COMPILES deps/, and the image must not carry it at all --
# 1.1G of vendored source that the image has no use for now that provenance
# ships as deps/dep_info.json instead.
#
# The image's list is generated from the shared one rather than maintained
# beside it: the common entries are build outputs (iso/, raw/, images/, ...) and
# a copy that drifts would silently start shipping one of them.
IMAGE_IGNOREFILE := .containerignore.image

# The image ships provenance instead of source: which commit of which
# repository produced each binary. Regenerated on every build so it can never
# describe a tree other than the one being built.
DEP_INFO := artifacts/overrides/usr/immutablue/deps/dep_info.json

.PHONY: deps_manifest
deps_manifest:
	@./scripts/gen-dep-info.sh $(DEP_INFO)

$(IMAGE_IGNOREFILE): .containerignore
	@cat $< > $@
	@printf '\n# Generated by makefiles/30-build.mk -- edit .containerignore instead.\n' >> $@
	@printf '# The vendored submodules are compiled into the deps container\n' >> $@
	@printf '# (deps-container/Containerfile); the image ships dep_info.json instead.\n' >> $@
	@printf 'deps/\n' >> $@
	@printf '# ...and their histories, which are 2.7G of the 2.8G under .git.\n' >> $@
	@printf '# Both spellings: existing clones keep the pre-move gitdir path,\n' >> $@
	@printf '# a fresh clone creates the new one.\n' >> $@
	@printf '.git/modules/artifacts/\n' >> $@
	@printf '.git/modules/deps/\n' >> $@
	@printf '# NOT .git/modules/docs -- hugo enableGitInfo reads it in\n' >> $@
	@printf '# 90-post.sh, and without it the docs build fails outright.\n' >> $@

# ------------------------------------------------------------------------------
# Dependency Container Builds
# ------------------------------------------------------------------------------
build-deps:
	buildah \
		build \
		--ignorefile ./.containerignore \
		--no-cache \
		--platform $(PLATFORM) \
		-t $(DEPS_CONTAINER) \
		-t $(DEPS_CONTAINER_DATE) \
		-f ./deps-container/Containerfile \
		--build-arg=BASE_IMAGE=$(BASE_IMAGE) \
		--build-arg=FEDORA_VERSION=$(VERSION) \
		--build-arg=IMAGE_TAG=$(IMAGE_BASE_TAG):$(TAG) \
		--build-arg=DO_INSTALL_LTS=$(DO_INSTALL_LTS) \
		--build-arg=DO_INSTALL_ZFS=$(DO_INSTALL_ZFS) \
		--build-arg=DO_INSTALL_AKMODS=$(DO_INSTALL_AKMODS) \
		--build-arg=IMMUTABLUE_BUILD_OPTIONS=$(BUILD_OPTIONS)

push-deps:
	buildah push $(DEPS_CONTAINER)
	buildah push $(DEPS_CONTAINER_DATE)

# ------------------------------------------------------------------------------
# NVIDIA/Cyan Dependency Build
# ------------------------------------------------------------------------------
build-cyan-deps:
	buildah \
		build \
		--no-cache \
		--platform $(PLATFORM) \
		-t $(CYAN_DEPS_CONTAINER) \
		-t $(CYAN_DEPS_CONTAINER_DATE) \
		-f ./deps-container/cyan/Containerfile \
		--build-arg=FEDORA_VERSION=$(VERSION)

push-cyan-deps:
	buildah push $(CYAN_DEPS_CONTAINER)
	buildah push $(CYAN_DEPS_CONTAINER_DATE)

# ------------------------------------------------------------------------------
# Main Container Build
# ------------------------------------------------------------------------------
build: pre_test deps_manifest $(IMAGE_IGNOREFILE)
ifeq ($(DISTROLESS),1)
	sudo podman \
		build \
		--format oci \
		--security-opt label=disable \
		--squash-all \
		--ignorefile ./$(IMAGE_IGNOREFILE) \
		--no-cache \
		-t $(IMAGE):$(TAG) \
		-f ./Containerfile \
		--build-arg=BASE_IMAGE=$(BASE_IMAGE) \
		--build-arg=BASE_IMAGE_TAG=$(BASE_IMAGE_TAG) \
		--build-arg=BASE_IMAGE_DEVEL=$(BASE_IMAGE_DEVEL) \
		--build-arg=IS_DISTROLESS=$(IS_DISTROLESS) \
		--build-arg=FEDORA_VERSION=$(VERSION) \
		--build-arg=IMAGE_TAG=$(IMAGE_BASE_TAG):$(TAG) \
		--build-arg=DO_INSTALL_LTS=$(DO_INSTALL_LTS) \
		--build-arg=DO_INSTALL_ZFS=$(DO_INSTALL_ZFS) \
		--build-arg=DO_INSTALL_AKMODS=$(DO_INSTALL_AKMODS) \
		--build-arg=IMMUTABLUE_BUILD_OPTIONS=$(BUILD_OPTIONS) \
		--build-arg=SKIP=$(SKIP)
	sudo podman tag $(IMAGE):$(TAG) $(IMAGE):$(DATE_TAG)
else
	buildah \
		build \
		--ignorefile ./$(IMAGE_IGNOREFILE) \
		--no-cache \
		-t $(IMAGE):$(TAG) \
		-t $(IMAGE):$(DATE_TAG) \
		-f ./Containerfile \
		--build-arg=BASE_IMAGE=$(BASE_IMAGE) \
		--build-arg=BASE_IMAGE_TAG=$(BASE_IMAGE_TAG) \
		--build-arg=BASE_IMAGE_DEVEL=$(BASE_IMAGE_DEVEL) \
		--build-arg=IS_DISTROLESS=$(IS_DISTROLESS) \
		--build-arg=FEDORA_VERSION=$(VERSION) \
		--build-arg=IMAGE_TAG=$(IMAGE_BASE_TAG):$(TAG) \
		--build-arg=DO_INSTALL_LTS=$(DO_INSTALL_LTS) \
		--build-arg=DO_INSTALL_ZFS=$(DO_INSTALL_ZFS) \
		--build-arg=DO_INSTALL_AKMODS=$(DO_INSTALL_AKMODS) \
		--build-arg=IMMUTABLUE_BUILD_OPTIONS=$(BUILD_OPTIONS) \
		--build-arg=SKIP=$(SKIP)
endif

# ------------------------------------------------------------------------------
# Push Targets
# ------------------------------------------------------------------------------
push:
ifeq ($(SET_AS_LATEST), 1)
	buildah push $(IMAGE):latest
endif
	buildah push $(IMAGE):$(TAG)
	buildah push $(IMAGE):$(DATE_TAG)

retag:
	buildah tag $(IMAGE):$(TAG) $(IMAGE):$(RETAG)

# ------------------------------------------------------------------------------
# Flatpak References
# ------------------------------------------------------------------------------
flatpak_refs/flatpaks: packages.yaml
	mkdir -p ./flatpak_refs
	bash -c 'source ./scripts/packages.sh && flatpak_make_refs'

# ------------------------------------------------------------------------------
# Manifest Management
# ------------------------------------------------------------------------------
manifest:
	buildah manifest create $(IMAGE):$(TAG)
	buildah manifest add $(IMAGE):$(TAG) docker://$(IMAGE):$(TAG)-amd64
	buildah manifest add $(IMAGE):$(TAG) docker://$(IMAGE):$(TAG)-arm64
	buildah manifest push --all $(IMAGE):$(TAG) docker://$(IMAGE):$(TAG)

manifest_rm:
	-buildah manifest rm $(IMAGE):$(TAG) 2>/dev/null || true

# ------------------------------------------------------------------------------
# Cleanup (safe for shared storage -- only removes images this job built)
# ------------------------------------------------------------------------------
clean-deps:
	-buildah rmi --force $(DEPS_CONTAINER) $(DEPS_CONTAINER_DATE) 2>/dev/null || true

clean-cyan-deps:
	-buildah rmi --force $(CYAN_DEPS_CONTAINER) $(CYAN_DEPS_CONTAINER_DATE) 2>/dev/null || true

clean-build:
ifeq ($(SET_AS_LATEST), 1)
	-buildah rmi --force $(IMAGE):latest 2>/dev/null || true
endif
	-buildah rmi --force $(IMAGE):$(TAG) $(IMAGE):$(DATE_TAG) 2>/dev/null || true
