# ==============================================================================
# Immutablue Build System - VM Targets (QCOW2, Lima)
# ==============================================================================
# This file contains QCOW2 image generation and Lima VM management targets.
# ==============================================================================

# ------------------------------------------------------------------------------
# QCOW2 Image Generation
# ------------------------------------------------------------------------------
qcow2-config:
	@echo "=== Immutablue QCOW2 Image Configuration ==="
	@echo "Config file: $(QCOW2_DIR)/config-$(TAG).toml"
	@echo ""
	@./scripts/generate-image-config.sh qcow2 $(QCOW2_DIR)/config-$(TAG).toml $(if $(filter 1,$(LIMA)),--lima)

qcow2: _check_not_distroless
	@echo "Building qcow2 VM image for $(IMAGE):$(TAG)..."
	@mkdir -p $(QCOW2_DIR)
	@if [ -f "$(QCOW2_DIR)/config-$(TAG).toml" ]; then \
		echo "Using existing config: $(QCOW2_DIR)/config-$(TAG).toml"; \
		cp $(QCOW2_DIR)/config-$(TAG).toml $(QCOW2_DIR)/config.toml; \
	elif [ "$(LIMA)" = "1" ]; then \
		echo "LIMA=1: Generating config with SSH keys..."; \
		./scripts/generate-image-config.sh qcow2 $(QCOW2_DIR)/config.toml --lima --non-interactive; \
	else \
		echo "No config found - creating default config (immutablue/immutablue)"; \
		echo "Tip: Run 'make qcow2-config' for interactive configuration"; \
		./scripts/generate-image-config.sh qcow2 $(QCOW2_DIR)/config.toml --non-interactive; \
	fi
	sudo podman pull $(IMAGE):$(TAG)
	sudo podman run \
		--rm -it --privileged \
		--security-opt label=type:unconfined_t \
		-v $(QCOW2_DIR):/output:z \
		-v /var/lib/containers/storage:/var/lib/containers/storage \
		-v $(QCOW2_DIR)/config.toml:/config.toml:ro \
		$(BOOTC_IMAGE_BUILDER) \
		--type qcow2 --rootfs btrfs --config /config.toml \
		$(IMAGE):$(TAG)
	sudo chown -R $$(id -u):$$(id -g) $(QCOW2_DIR)
	@echo "qcow2 image built: $(QCOW2_DIR)/qcow2/disk.qcow2"

run_qcow2:
	@echo "Booting $(QCOW2_DIR)/qcow2/disk.qcow2..."
	@echo "SSH: ssh -p 2222 immutablue@localhost (password: immutablue)"
	@echo "Exit: Ctrl-A X"
	sudo qemu-system-x86_64 \
		-enable-kvm -m 4G -smp 4 -cpu host \
		-drive file=$(QCOW2_DIR)/qcow2/disk.qcow2,format=qcow2 \
		-boot c \
		-nic user,hostfwd=tcp::2222-:22 \
		-nographic -serial mon:stdio

# ------------------------------------------------------------------------------
# Lima VM Management
# ------------------------------------------------------------------------------
lima:
	@echo "Generating Lima config for $(LIMA_INSTANCE)..."
	@mkdir -p $(LIMA_DIR)
	@echo "# Lima configuration for $(IMAGE):$(TAG)" > $(LIMA_YAML)
	@echo "# Generated by: make lima" >> $(LIMA_YAML)
	@echo "# Auto-generated file - do not edit manually" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo 'minimumLimaVersion: "2.0.0"' >> $(LIMA_YAML)
	@echo "vmType: qemu" >> $(LIMA_YAML)
	@echo "arch: x86_64" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "user:" >> $(LIMA_YAML)
	@echo "  name: immutablue" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "images:" >> $(LIMA_YAML)
	@echo '- location: "$(CURDIR)/$(QCOW2_DIR)/qcow2/disk.qcow2"' >> $(LIMA_YAML)
	@echo '  arch: "x86_64"' >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "cpus: 4" >> $(LIMA_YAML)
	@echo 'memory: "4GiB"' >> $(LIMA_YAML)
	@echo 'disk: "100GiB"' >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "mounts:" >> $(LIMA_YAML)
	@echo '- location: "~"' >> $(LIMA_YAML)
	@echo "  writable: false" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "ssh:" >> $(LIMA_YAML)
	@echo "  localPort: 0" >> $(LIMA_YAML)
	@echo "  loadDotSSHPubKeys: true" >> $(LIMA_YAML)
	@echo "  # Fedora 43 SELinux issue with vsock" >> $(LIMA_YAML)
	@echo "  overVsock: false" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "containerd:" >> $(LIMA_YAML)
	@echo "  system: false" >> $(LIMA_YAML)
	@echo "  user: false" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "# Skip Lima guest agent for pre-built bootc images" >> $(LIMA_YAML)
	@echo "plain: true" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "# Probe to signal boot is complete" >> $(LIMA_YAML)
	@echo "probes:" >> $(LIMA_YAML)
	@echo "- mode: readiness" >> $(LIMA_YAML)
	@echo "  description: vm is ready" >> $(LIMA_YAML)
	@echo "  script: |" >> $(LIMA_YAML)
	@echo "    #!/bin/bash" >> $(LIMA_YAML)
	@echo "    true" >> $(LIMA_YAML)
	@echo "" >> $(LIMA_YAML)
	@echo "message: |" >> $(LIMA_YAML)
	@echo "  Immutablue VM ($(TAG))" >> $(LIMA_YAML)
	@echo "  Default user: immutablue (password: immutablue)" >> $(LIMA_YAML)
	@echo "  Commands:" >> $(LIMA_YAML)
	@echo "    limactl shell $(LIMA_INSTANCE)" >> $(LIMA_YAML)
	@echo "    limactl stop $(LIMA_INSTANCE)" >> $(LIMA_YAML)
	@echo "    limactl delete $(LIMA_INSTANCE)" >> $(LIMA_YAML)
	@echo ""
	@echo "Lima config generated: $(LIMA_YAML)"
	@echo "Run 'make lima-start' to start the VM"

lima-start:
	@if [ ! -f "$(LIMA_YAML)" ]; then \
		echo "Lima config not found. Run 'make lima' first."; \
		exit 1; \
	fi
	@echo "Starting Lima VM $(LIMA_INSTANCE)..."
	limactl start $(LIMA_YAML)
	@echo ""
	@echo "VM started! Use 'make lima-shell' or 'limactl shell $(LIMA_INSTANCE)'"

lima-shell:
	limactl shell $(LIMA_INSTANCE)

lima-stop:
	limactl stop $(LIMA_INSTANCE)

lima-delete:
	limactl delete $(LIMA_INSTANCE)

# ------------------------------------------------------------------------------
# Distroless Image Generation
# ------------------------------------------------------------------------------
distroless-img:
ifneq ($(DISTROLESS),1)
	@echo "ERROR: distroless-img target requires DISTROLESS=1"
	@echo "Usage: make DISTROLESS=1 distroless-img"
	@exit 1
endif
	@echo "Building bootable disk image for $(IMAGE):$(TAG)..."
	@mkdir -p $(DISTROLESS_DIR)
	@rm -f "$(DISTROLESS_IMG)"
	IMAGE_SIZE=$(DISTROLESS_IMG_SIZE) ./build/distroless/build-disk-image.sh \
		"$(DISTROLESS_IMG)" \
		"$(IMAGE):$(TAG)" \
		"$(DISTROLESS_FILESYSTEM)"
	sudo chown -R $$(id -u):$$(id -g) $(DISTROLESS_DIR)
	@echo ""
	@echo "Bootable image created: $(DISTROLESS_IMG)"
	@echo "Run with: make DISTROLESS=1 run-distroless-img"

run-distroless-img:
ifneq ($(DISTROLESS),1)
	@echo "ERROR: run-distroless-img target requires DISTROLESS=1"
	@exit 1
endif
	@echo "Booting $(DISTROLESS_IMG)..."
	@echo "Exit: Ctrl-A X"
	@if command -v qemu-system-x86_64 >/dev/null 2>&1; then \
		QEMU="qemu-system-x86_64"; \
		OVMF="/usr/share/edk2/ovmf/OVMF_CODE_4M.qcow2"; \
		OVMF_FMT="qcow2"; \
	else \
		echo "qemu-system-x86_64 not found. Install qemu or use flatpak."; \
		exit 1; \
	fi; \
	sudo $$QEMU \
		-machine pc-q35-10.1 \
		-m 8G \
		-smp 4 \
		-cpu host \
		-enable-kvm \
		-device virtio-vga \
		-drive if=pflash,format=$$OVMF_FMT,readonly=on,file=$$OVMF \
		-drive file=$(DISTROLESS_IMG),format=raw,if=virtio \
		-nic user,hostfwd=tcp::2222-:22 \
		-nographic \
		-serial mon:stdio

distroless-qcow2: distroless-img
	@echo "Converting $(DISTROLESS_IMG) to qcow2..."
	qemu-img convert -f raw -O qcow2 $(DISTROLESS_IMG) $(DISTROLESS_DIR)/bootable-$(TAG).qcow2
	@echo "qcow2 image created: $(DISTROLESS_DIR)/bootable-$(TAG).qcow2"

distroless-clean:
	rm -rf $(DISTROLESS_DIR)

# ------------------------------------------------------------------------------
# Virsh Fix
# ------------------------------------------------------------------------------
VM ?=
fix-virsh:
ifndef VM
	@echo "ERROR: VM name required"
	@echo "Usage: make VM=<vm_name> fix-virsh"
	@exit 1
endif
	@./build/distroless/fix-virsh.sh "$(VM)"
